<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['id' => Str::uuid(), 'provider_code' => '01907DR008', 'nama' => 'KLINIK MEDIS PUSURA CANDI', 'role' => 'provider', 'is_active' => true, 'email' => '01907-klinikmedispusuracandi329@nayakaerahusada.com', 'username' => 'PUSURA_CAN', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907PS001', 'nama' => 'KLINIK MEDIS PUSURA BALONGSARI', 'role' => 'provider', 'is_active' => true, 'email' => '01907-klinikmedispusurabalongsari68@nayakaerahusada.com', 'username' => 'PUSURA_BALO', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907PS002', 'nama' => 'RS PUSURA TEGALSARI', 'role' => 'provider', 'is_active' => true, 'email' => '01907-rspusurategalsari639@nayakaerahusada.com', 'username' => 'PUSURA_TE', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907PS005', 'nama' => 'KLINIK MEDIS PUSURA RUNGKUT', 'role' => 'provider', 'is_active' => true, 'email' => '01907-klinikmedispusurarungkut909@nayakaerahusada.com', 'username' => 'PUSURA_RU', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907PS019', 'nama' => 'KLINIK MEDIS PUSURA SUNGKONO', 'role' => 'provider', 'is_active' => true, 'email' => '01907-klinikmedispusurasungkono843@nayakaerahusada.com', 'username' => 'PUSURA_SU', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '191306002', 'nama' => 'KLINIK UTAMA RAWAT INAP YOS SUDARSO', 'role' => 'provider', 'is_active' => true, 'email' => '19130-klinikutamarawatinapyossudarso958@nayakaerahusada.com', 'username' => 'PUSURA_YO', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '191109002', 'nama' => 'RS MITRA KELUARGA WARU', 'role' => 'provider', 'is_active' => true, 'email' => '19110-rsmitrakeluargawaru764@nayakaerahusada.com', 'username' => 'MK_WARU_RAJAL1', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '191109002', 'nama' => 'RS MITRA KELUARGA WARU', 'role' => 'provider', 'is_active' => true, 'email' => '19110-rsmitrakeluargawaru960@nayakaerahusada.com', 'username' => 'MK_WARU_RAJAL2', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '191109002', 'nama' => 'RS MITRA KELUARGA WARU', 'role' => 'provider', 'is_active' => true, 'email' => '19110-rsmitrakeluargawaru636@nayakaerahusada.com', 'username' => 'MK_WARU_RANAP1', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '191109002', 'nama' => 'RS MITRA KELUARGA WARU', 'role' => 'provider', 'is_active' => true, 'email' => '19110-rsmitrakeluargawaru549@nayakaerahusada.com', 'username' => 'MK_WARU_RANAP2', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '191109002', 'nama' => 'RS MITRA KELUARGA WARU', 'role' => 'provider', 'is_active' => true, 'email' => '19110-rsmitrakeluargawaru76@nayakaerahusada.com', 'username' => 'MK_WARU_FARM1', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '191109002', 'nama' => 'RS MITRA KELUARGA WARU', 'role' => 'provider', 'is_active' => true, 'email' => '19110-rsmitrakeluargawaru841@nayakaerahusada.com', 'username' => 'MK_WARU_FARM2', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '191109002', 'nama' => 'RS MITRA KELUARGA WARU', 'role' => 'provider', 'is_active' => true, 'email' => '19110-rsmitrakeluargawaru417@nayakaerahusada.com', 'username' => 'MK_WARU_FIN', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907GR011', 'nama' => 'RS MITRA KELUARGA PONDOK TJANDRA', 'role' => 'provider', 'is_active' => true, 'email' => '01907-rsmitrakeluargapondoktjandra141@nayakaerahusada.com', 'username' => 'MK_POCAN_RAJAL1', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907GR011', 'nama' => 'RS MITRA KELUARGA PONDOK TJANDRA', 'role' => 'provider', 'is_active' => true, 'email' => '01907-rsmitrakeluargapondoktjandra466@nayakaerahusada.com', 'username' => 'MK_POCAN_RAJAL2', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907GR011', 'nama' => 'RS MITRA KELUARGA PONDOK TJANDRA', 'role' => 'provider', 'is_active' => true, 'email' => '01907-rsmitrakeluargapondoktjandra75@nayakaerahusada.com', 'username' => 'MK_POCAN_RANAP', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907GR011', 'nama' => 'RS MITRA KELUARGA PONDOK TJANDRA', 'role' => 'provider', 'is_active' => true, 'email' => '01907-rsmitrakeluargapondoktjandra807@nayakaerahusada.com', 'username' => 'MK_POCAN_FARM', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907GR011', 'nama' => 'RS MITRA KELUARGA PONDOK TJANDRA', 'role' => 'provider', 'is_active' => true, 'email' => '01907-rsmitrakeluargapondoktjandra691@nayakaerahusada.com', 'username' => 'MK_POCAN_FIN', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '326001691', 'nama' => 'RS MITRA KELUARGA KENJERAN', 'role' => 'provider', 'is_active' => true, 'email' => '32600-rsmitrakeluargakenjeran994@nayakaerahusada.com', 'username' => 'MK_KENJ_RAJAL', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '326001691', 'nama' => 'RS MITRA KELUARGA KENJERAN', 'role' => 'provider', 'is_active' => true, 'email' => '32600-rsmitrakeluargakenjeran398@nayakaerahusada.com', 'username' => 'MK_KENJ_RANAP', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '326001691', 'nama' => 'RS MITRA KELUARGA KENJERAN', 'role' => 'provider', 'is_active' => true, 'email' => '32600-rsmitrakeluargakenjeran38@nayakaerahusada.com', 'username' => 'MK_KENJ_FARM', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '326001691', 'nama' => 'RS MITRA KELUARGA KENJERAN', 'role' => 'provider', 'is_active' => true, 'email' => '32600-rsmitrakeluargakenjeran96@nayakaerahusada.com', 'username' => 'MK_KENJ_FIN', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '191109001', 'nama' => 'RS MITRA KELUARGA SURABAYA', 'role' => 'provider', 'is_active' => true, 'email' => '19110-rsmitrakeluargasurabaya830@nayakaerahusada.com', 'username' => 'MK_SBY_RAJAL1', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '191109001', 'nama' => 'RS MITRA KELUARGA SURABAYA', 'role' => 'provider', 'is_active' => true, 'email' => '19110-rsmitrakeluargasurabaya10@nayakaerahusada.com', 'username' => 'MK_SBY_RAJAL2', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '191109001', 'nama' => 'RS MITRA KELUARGA SURABAYA', 'role' => 'provider', 'is_active' => true, 'email' => '19110-rsmitrakeluargasurabaya787@nayakaerahusada.com', 'username' => 'MK_SBY_RANAP1', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '191109001', 'nama' => 'RS MITRA KELUARGA SURABAYA', 'role' => 'provider', 'is_active' => true, 'email' => '19110-rsmitrakeluargasurabaya74@nayakaerahusada.com', 'username' => 'MK_SBY_RANAP2', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '191109001', 'nama' => 'RS MITRA KELUARGA SURABAYA', 'role' => 'provider', 'is_active' => true, 'email' => '19110-rsmitrakeluargasurabaya216@nayakaerahusada.com', 'username' => 'MK_SBY_FARM', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '191109001', 'nama' => 'RS MITRA KELUARGA SURABAYA', 'role' => 'provider', 'is_active' => true, 'email' => '19110-rsmitrakeluargasurabaya930@nayakaerahusada.com', 'username' => 'MK_SBY_FIN', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '1a', 'nama' => 'RS KENDANGSARI', 'role' => 'provider', 'is_active' => true, 'email' => '1a-rskendangsari757@nayakaerahusada.com', 'username' => 'KendangsariRj1', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '1a', 'nama' => 'RS KENDANGSARI', 'role' => 'provider', 'is_active' => true, 'email' => '1a-rskendangsari594@nayakaerahusada.com', 'username' => 'KendangsariRj2', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '1a', 'nama' => 'RS KENDANGSARI', 'role' => 'provider', 'is_active' => true, 'email' => '1a-rskendangsari592@nayakaerahusada.com', 'username' => 'KendangsariRj3', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '1a', 'nama' => 'RS KENDANGSARI', 'role' => 'provider', 'is_active' => true, 'email' => '1a-rskendangsari120@nayakaerahusada.com', 'username' => 'KendangsariRi', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '1a', 'nama' => 'RS KENDANGSARI', 'role' => 'provider', 'is_active' => true, 'email' => '1a-rskendangsari28@nayakaerahusada.com', 'username' => 'KendangsariFarm', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '1a', 'nama' => 'RS KENDANGSARI', 'role' => 'provider', 'is_active' => true, 'email' => '1a-rskendangsari24@nayakaerahusada.com', 'username' => 'KendangsariFin', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '325001357', 'nama' => 'RS PELENGKAP MEDICAL CENTER JOMBANG', 'role' => 'provider', 'is_active' => true, 'email' => '32500-rspelengkapmedicalcenterjombang366@nayakaerahusada.com', 'username' => 'PelengkapRJ', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '325001357', 'nama' => 'RS PELENGKAP MEDICAL CENTER JOMBANG', 'role' => 'provider', 'is_active' => true, 'email' => '32500-rspelengkapmedicalcenterjombang575@nayakaerahusada.com', 'username' => 'PelengkapRI', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '325001357', 'nama' => 'RS PELENGKAP MEDICAL CENTER JOMBANG', 'role' => 'provider', 'is_active' => true, 'email' => '32500-rspelengkapmedicalcenterjombang871@nayakaerahusada.com', 'username' => 'PelengkapAdmin', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '325001357', 'nama' => 'RS PELENGKAP MEDICAL CENTER JOMBANG', 'role' => 'provider', 'is_active' => true, 'email' => '32500-rspelengkapmedicalcenterjombang56@nayakaerahusada.com', 'username' => 'PelengkapFarms', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '019-0017', 'nama' => 'RS SILOAM MAKASAR', 'role' => 'provider', 'is_active' => true, 'email' => '019-0-rssiloammakasar603@nayakaerahusada.com', 'username' => 'SiloamMksRi', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '019-0017', 'nama' => 'RS SILOAM MAKASAR', 'role' => 'provider', 'is_active' => true, 'email' => '019-0-rssiloammakasar757@nayakaerahusada.com', 'username' => 'SiloamMksRj', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '019-0017', 'nama' => 'RS SILOAM MAKASAR', 'role' => 'provider', 'is_active' => true, 'email' => '019-0-rssiloammakasar855@nayakaerahusada.com', 'username' => 'SiloamMksAdm', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '019-0017', 'nama' => 'RS SILOAM MAKASAR', 'role' => 'provider', 'is_active' => true, 'email' => '019-0-rssiloammakasar353@nayakaerahusada.com', 'username' => 'SiloamMksFrm', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '191107003', 'nama' => 'RS SILOAM SURABAYA', 'role' => 'provider', 'is_active' => true, 'email' => '19110-rssiloamsurabaya27@nayakaerahusada.com', 'username' => 'SiloamSbyAdm', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '191107003', 'nama' => 'RS SILOAM SURABAYA', 'role' => 'provider', 'is_active' => true, 'email' => '19110-rssiloamsurabaya606@nayakaerahusada.com', 'username' => 'SiloamSbyRi', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '191107003', 'nama' => 'RS SILOAM SURABAYA', 'role' => 'provider', 'is_active' => true, 'email' => '19110-rssiloamsurabaya639@nayakaerahusada.com', 'username' => 'SiloamSbyRj', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '191107003', 'nama' => 'RS SILOAM SURABAYA', 'role' => 'provider', 'is_active' => true, 'email' => '19110-rssiloamsurabaya761@nayakaerahusada.com', 'username' => 'SiloamSbyFarm', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '019-0054', 'nama' => 'RS GATOEL MOJOKERTO', 'role' => 'provider', 'is_active' => true, 'email' => '019-0-rsgatoelmojokerto524@nayakaerahusada.com', 'username' => 'GatoelRj', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '019-0054', 'nama' => 'RS GATOEL MOJOKERTO', 'role' => 'provider', 'is_active' => true, 'email' => '019-0-rsgatoelmojokerto744@nayakaerahusada.com', 'username' => 'GatoelRi', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '019-0054', 'nama' => 'RS GATOEL MOJOKERTO', 'role' => 'provider', 'is_active' => true, 'email' => '019-0-rsgatoelmojokerto310@nayakaerahusada.com', 'username' => 'GatoelFarm1', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '019-0054', 'nama' => 'RS GATOEL MOJOKERTO', 'role' => 'provider', 'is_active' => true, 'email' => '019-0-rsgatoelmojokerto460@nayakaerahusada.com', 'username' => 'GatoelFarm2', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '019-0054', 'nama' => 'RS GATOEL MOJOKERTO', 'role' => 'provider', 'is_active' => true, 'email' => '019-0-rsgatoelmojokerto55@nayakaerahusada.com', 'username' => 'GatoelFin', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907DR008', 'nama' => 'KLINIK MEDIS PUSURA CANDI', 'role' => 'provider', 'is_active' => true, 'email' => '01907-klinikmedispusuracandi869@nayakaerahusada.com', 'username' => 'PUSURA_CAN', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907PS001', 'nama' => 'KLINIK MEDIS PUSURA BALONGSARI', 'role' => 'provider', 'is_active' => true, 'email' => '01907-klinikmedispusurabalongsari71@nayakaerahusada.com', 'username' => 'PUSURA_BALO', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907PS002', 'nama' => 'RS PUSURA TEGALSARI', 'role' => 'provider', 'is_active' => true, 'email' => '01907-rspusurategalsari63@nayakaerahusada.com', 'username' => 'PUSURA_TE', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907PS005', 'nama' => 'KLINIK MEDIS PUSURA RUNGKUT', 'role' => 'provider', 'is_active' => true, 'email' => '01907-klinikmedispusurarungkut47@nayakaerahusada.com', 'username' => 'PUSURA_RU', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907PS019', 'nama' => 'KLINIK MEDIS PUSURA SUNGKONO', 'role' => 'provider', 'is_active' => true, 'email' => '01907-klinikmedispusurasungkono192@nayakaerahusada.com', 'username' => 'PUSURA_SU', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '191306002', 'nama' => 'KLINIK UTAMA RAWAT INAP YOS SUDARSO', 'role' => 'provider', 'is_active' => true, 'email' => '19130-klinikutamarawatinapyossudarso41@nayakaerahusada.com', 'username' => 'PUSURA_YO', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '019-0007', 'nama' => 'OPTIK PRADHANA', 'role' => 'provider', 'is_active' => true, 'email' => '019-0-optikpradhana713@nayakaerahusada.com', 'username' => 'PRADANAOptRkt1', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '019-0007', 'nama' => 'OPTIK PRADHANA', 'role' => 'provider', 'is_active' => true, 'email' => '019-0-optikpradhana480@nayakaerahusada.com', 'username' => 'PRADANAOptRkt2', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '191107002', 'nama' => 'APOTEK PRADHANA', 'role' => 'provider', 'is_active' => true, 'email' => '19110-apotekpradhana860@nayakaerahusada.com', 'username' => 'PRADANArkt1', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '191107002', 'nama' => 'APOTEK PRADHANA', 'role' => 'provider', 'is_active' => true, 'email' => '19110-apotekpradhana353@nayakaerahusada.com', 'username' => 'PRADANAAptRkt2', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '190812003', 'nama' => 'OPTIK MARLIN SOLATAMA', 'role' => 'provider', 'is_active' => true, 'email' => '19081-optikmarlinsolatama588@nayakaerahusada.com', 'username' => 'APTMARLIN', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '191112008', 'nama' => 'OPTIK BERLIAN', 'role' => 'provider', 'is_active' => true, 'email' => '19111-optikberlian566@nayakaerahusada.com', 'username' => 'OPTBERLIAN', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '191112001', 'nama' => 'OPTIK JOYO MULYO', 'role' => 'provider', 'is_active' => true, 'email' => '19111-optikjoyomulyo760@nayakaerahusada.com', 'username' => 'OPTJOYOMULYO', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '819000029', 'nama' => 'OPTIK JOYO BARU', 'role' => 'provider', 'is_active' => true, 'email' => '81900-optikjoyobaru611@nayakaerahusada.com', 'username' => 'OPTJOYOBARU', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '191306004', 'nama' => 'KLINIK MEDIS GELORA', 'role' => 'provider', 'is_active' => true, 'email' => '19130-klinikmedisgelora332@nayakaerahusada.com', 'username' => 'klinik_gelora1', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '191306004', 'nama' => 'KLINIK MEDIS GELORA', 'role' => 'provider', 'is_active' => true, 'email' => '19130-klinikmedisgelora774@nayakaerahusada.com', 'username' => 'klinik_gelora2', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '019-0032', 'nama' => 'KLINIK SEHAT / FARIDA SEHAT MAKASSAR', 'role' => 'provider', 'is_active' => true, 'email' => '019-0-kliniksehat/faridasehatmakassar529@nayakaerahusada.com', 'username' => 'klinik_sehat1', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '019-0032', 'nama' => 'KLINIK SEHAT / FARIDA SEHAT MAKASSAR', 'role' => 'provider', 'is_active' => true, 'email' => '019-0-kliniksehat/faridasehatmakassar820@nayakaerahusada.com', 'username' => 'klinik_sehat2', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '019-0033', 'nama' => 'APOTEK RAKYAT MANADO', 'role' => 'provider', 'is_active' => true, 'email' => '019-0-apotekrakyatmanado996@nayakaerahusada.com', 'username' => 'apotek_rakyat1', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '019-0033', 'nama' => 'APOTEK RAKYAT MANADO', 'role' => 'provider', 'is_active' => true, 'email' => '019-0-apotekrakyatmanado95@nayakaerahusada.com', 'username' => 'apotek_rakyat2', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '019-0014', 'nama' => 'RS PRIMAYA MAKASAR EX RS AWALBROS', 'role' => 'provider', 'is_active' => true, 'email' => '019-0-rsprimayamakasarexrsawalbros309@nayakaerahusada.com', 'username' => 'PrimayaMks1', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '019-0014', 'nama' => 'RS PRIMAYA MAKASAR EX RS AWALBROS', 'role' => 'provider', 'is_active' => true, 'email' => '019-0-rsprimayamakasarexrsawalbros383@nayakaerahusada.com', 'username' => 'PrimayaMks2', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '019-0014', 'nama' => 'RS PRIMAYA MAKASAR EX RS AWALBROS', 'role' => 'provider', 'is_active' => true, 'email' => '019-0-rsprimayamakasarexrsawalbros233@nayakaerahusada.com', 'username' => 'PrimayaMks3', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '019-0014', 'nama' => 'RS PRIMAYA MAKASAR EX RS AWALBROS', 'role' => 'provider', 'is_active' => true, 'email' => '019-0-rsprimayamakasarexrsawalbros67@nayakaerahusada.com', 'username' => 'PrimayaMks4', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '124000934', 'nama' => 'RS PRIMAYA HERTASNING MAKASAR', 'role' => 'provider', 'is_active' => true, 'email' => '12400-rsprimayahertasningmakasar658@nayakaerahusada.com', 'username' => 'PrimayaHer4', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '124000934', 'nama' => 'RS PRIMAYA HERTASNING MAKASAR', 'role' => 'provider', 'is_active' => true, 'email' => '12400-rsprimayahertasningmakasar769@nayakaerahusada.com', 'username' => 'PrimayaHer3', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '124000934', 'nama' => 'RS PRIMAYA HERTASNING MAKASAR', 'role' => 'provider', 'is_active' => true, 'email' => '12400-rsprimayahertasningmakasar106@nayakaerahusada.com', 'username' => 'PrimayaHer2', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '124000934', 'nama' => 'RS PRIMAYA HERTASNING MAKASAR', 'role' => 'provider', 'is_active' => true, 'email' => '12400-rsprimayahertasningmakasar635@nayakaerahusada.com', 'username' => 'PrimayaHer1', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '2a', 'nama' => 'RS. PRIMAYA INCO SUROWAKO', 'role' => 'provider', 'is_active' => true, 'email' => '2a-rs.primayaincosurowako551@nayakaerahusada.com', 'username' => 'PrimayaSwk1', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '2a', 'nama' => 'RS. PRIMAYA INCO SUROWAKO', 'role' => 'provider', 'is_active' => true, 'email' => '2a-rs.primayaincosurowako529@nayakaerahusada.com', 'username' => 'PrimayaSwk2', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '2a', 'nama' => 'RS. PRIMAYA INCO SUROWAKO', 'role' => 'provider', 'is_active' => true, 'email' => '2a-rs.primayaincosurowako889@nayakaerahusada.com', 'username' => 'PrimayaSwk3', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '2a', 'nama' => 'RS. PRIMAYA INCO SUROWAKO', 'role' => 'provider', 'is_active' => true, 'email' => '2a-rs.primayaincosurowako84@nayakaerahusada.com', 'username' => 'PrimayaSwk4', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '019-0004', 'nama' => 'RS HERMINA MADIUN', 'role' => 'provider', 'is_active' => true, 'email' => '019-0-rsherminamadiun612@nayakaerahusada.com', 'username' => 'HerminaMadiun1', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '019-0004', 'nama' => 'RS HERMINA MADIUN', 'role' => 'provider', 'is_active' => true, 'email' => '019-0-rsherminamadiun909@nayakaerahusada.com', 'username' => 'HerminaMadiun2', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '019-0004', 'nama' => 'RS HERMINA MADIUN', 'role' => 'provider', 'is_active' => true, 'email' => '019-0-rsherminamadiun999@nayakaerahusada.com', 'username' => 'HerminaMadiun3', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '019-0004', 'nama' => 'RS HERMINA MADIUN', 'role' => 'provider', 'is_active' => true, 'email' => '019-0-rsherminamadiun848@nayakaerahusada.com', 'username' => 'HerminaMadiun4', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907KR010', 'nama' => 'RS HERMINA KENDARI', 'role' => 'provider', 'is_active' => true, 'email' => '01907-rsherminakendari151@nayakaerahusada.com', 'username' => 'HerminaKendari1', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907KR010', 'nama' => 'RS HERMINA KENDARI', 'role' => 'provider', 'is_active' => true, 'email' => '01907-rsherminakendari593@nayakaerahusada.com', 'username' => 'HerminaKendari2', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907KR010', 'nama' => 'RS HERMINA KENDARI', 'role' => 'provider', 'is_active' => true, 'email' => '01907-rsherminakendari820@nayakaerahusada.com', 'username' => 'HerminaKendari3', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907KR010', 'nama' => 'RS HERMINA KENDARI', 'role' => 'provider', 'is_active' => true, 'email' => '01907-rsherminakendari217@nayakaerahusada.com', 'username' => 'HerminaKendari4', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907ML028', 'nama' => 'RS HERMINA MANADO', 'role' => 'provider', 'is_active' => true, 'email' => '01907-rsherminamanado626@nayakaerahusada.com', 'username' => 'HerminaManado2', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907ML028', 'nama' => 'RS HERMINA MANADO', 'role' => 'provider', 'is_active' => true, 'email' => '01907-rsherminamanado803@nayakaerahusada.com', 'username' => 'HerminaManado3', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907ML028', 'nama' => 'RS HERMINA MANADO', 'role' => 'provider', 'is_active' => true, 'email' => '01907-rsherminamanado807@nayakaerahusada.com', 'username' => 'HerminaManado4', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907ML028', 'nama' => 'RS HERMINA MANADO', 'role' => 'provider', 'is_active' => true, 'email' => '01907-rsherminamanado605@nayakaerahusada.com', 'username' => 'HerminaManado5', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907TP007', 'nama' => 'RS HERMINA MAKASAR', 'role' => 'provider', 'is_active' => true, 'email' => '01907-rsherminamakasar512@nayakaerahusada.com', 'username' => 'HerminaMakasar1', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907TP007', 'nama' => 'RS HERMINA MAKASAR', 'role' => 'provider', 'is_active' => true, 'email' => '01907-rsherminamakasar201@nayakaerahusada.com', 'username' => 'HerminaMakasar2', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907TP007', 'nama' => 'RS HERMINA MAKASAR', 'role' => 'provider', 'is_active' => true, 'email' => '01907-rsherminamakasar774@nayakaerahusada.com', 'username' => 'HerminaMakasar3', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907TP007', 'nama' => 'RS HERMINA MAKASAR', 'role' => 'provider', 'is_active' => true, 'email' => '01907-rsherminamakasar473@nayakaerahusada.com', 'username' => 'HerminaMakasar4', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907PS008', 'nama' => 'RS UBAYA', 'role' => 'provider', 'is_active' => true, 'email' => '01907-rsubaya70@nayakaerahusada.com', 'username' => 'Ubaya1', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907PS008', 'nama' => 'RS UBAYA', 'role' => 'provider', 'is_active' => true, 'email' => '01907-rsubaya734@nayakaerahusada.com', 'username' => 'Ubaya2', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907PS008', 'nama' => 'RS UBAYA', 'role' => 'provider', 'is_active' => true, 'email' => '01907-rsubaya143@nayakaerahusada.com', 'username' => 'Ubaya3', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '01907PS008', 'nama' => 'RS UBAYA', 'role' => 'provider', 'is_active' => true, 'email' => '01907-rsubaya402@nayakaerahusada.com', 'username' => 'Ubaya4', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '190812005', 'nama' => 'RS KEMENKES SURABAYA', 'role' => 'provider', 'is_active' => true, 'email' => '19081-rskemenkessurabaya883@nayakaerahusada.com', 'username' => 'kemenkes1', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '190812005', 'nama' => 'RS KEMENKES SURABAYA', 'role' => 'provider', 'is_active' => true, 'email' => '19081-rskemenkessurabaya257@nayakaerahusada.com', 'username' => 'kemenkes2', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '190812005', 'nama' => 'RS KEMENKES SURABAYA', 'role' => 'provider', 'is_active' => true, 'email' => '19081-rskemenkessurabaya268@nayakaerahusada.com', 'username' => 'kemenkes3', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '190812005', 'nama' => 'RS KEMENKES SURABAYA', 'role' => 'provider', 'is_active' => true, 'email' => '19081-rskemenkessurabaya890@nayakaerahusada.com', 'username' => 'kemenkes4', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '190812005', 'nama' => 'RSUP KEMENKES MAKASSAR', 'role' => 'provider', 'is_active' => true, 'email' => '19081-rsupkemenkesmakassar83@nayakaerahusada.com', 'username' => 'kemenkesmks1', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '190812005', 'nama' => 'RSUP KEMENKES MAKASSAR', 'role' => 'provider', 'is_active' => true, 'email' => '19081-rsupkemenkesmakassar679@nayakaerahusada.com', 'username' => 'kemenkesmks2', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '190812005', 'nama' => 'RSUP KEMENKES MAKASSAR', 'role' => 'provider', 'is_active' => true, 'email' => '19081-rsupkemenkesmakassar564@nayakaerahusada.com', 'username' => 'kemenkesmks3', 'password' => bcrypt('12345678')],
            ['id' => Str::uuid(), 'provider_code' => '190812005', 'nama' => 'RSUP KEMENKES MAKASSAR', 'role' => 'provider', 'is_active' => true, 'email' => '19081-rsupkemenkesmakassar37@nayakaerahusada.com', 'username' => 'kemenkesmks4', 'password' => bcrypt('12345678')],
        ];
        DB::beginTransaction();
        try {
            foreach ($data as $row) {
                User::create($row);
            }
            Log::info('UserSeeder: Data pengguna berhasil ditambahkan.');
            DB::commit();
        } catch (\Throwable $th) {
            Log::error($th->getMessage());
            DB::rollback();
        }
    }
}
